FROM nginx:1.26-alpine
# Security: update packages
RUN apk update && \
    apk upgrade --available && \
    rm -rf /var/cache/apk/*
# Copy the custom NGINX configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copy built frontend from the 'dist' folder generated by GitLab CI
COPY dist/Front/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
