sonar.projectKey=m2gil_ollmark_ollmark-microservices_ollmark-backend_ms-ollmark-ia_692394de-b50c-41e1-8c3f-bb391d1950a2
sonar.qualitygate.wait=true
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts